import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from '../../global';

export const styles = StyleSheet.create({
  fullButton: {
    width: '100%',
    height: 54,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
    borderWidth: 1.5,
    borderColor: '#D92D20',
    borderRadius: 15,
    backgroundColor: colors.white,
  },
  fullButtonText: {
    color: '#D92D20',
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md ?? 15,
  },
  iconButton: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: colors.white,
  },
  overlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
    paddingHorizontal: 24,
  },
  dialog: {
    width: '100%',
    maxWidth: 390,
    alignItems: 'center',
    borderRadius: 18,
    backgroundColor: colors.white,
    paddingHorizontal: 24,
    paddingVertical: 26,
  },
  dialogIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 29,
    backgroundColor: '#FEF3F2',
    marginBottom: 15,
  },
  title: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: fontSizes.xl ?? 20,
  },
  message: {
    color: colors.cinza,
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm ?? 13,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 8,
  },
  error: {
    color: '#B42318',
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm ?? 12,
    textAlign: 'center',
    marginTop: 10,
  },
  actions: {
    width: '100%',
    flexDirection: 'row',
    gap: 10,
    marginTop: 23,
  },
  cancelButton: {
    flex: 1,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
    borderColor: '#C8C8C8',
    borderRadius: 12,
    backgroundColor: colors.white,
  },
  cancelButtonText: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md ?? 14,
  },
  confirmButton: {
    flex: 1,
    height: 46,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    backgroundColor: '#D92D20',
  },
  confirmButtonText: {
    color: colors.white,
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md ?? 14,
  },
});
