import { StyleSheet } from 'react-native';
import { colors, fontSizes, fonts } from '../../global';

const orange = '#FF6B2C';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: orange },
  header: { minHeight: 132, backgroundColor: orange, paddingHorizontal: 20, paddingTop: 10 },
  headerText: { marginTop: 16 },
  headerTitle: { color: '#FFFFFF', fontFamily: fonts.semibold, fontSize: fontSizes['2xl'] ?? 22 },
  headerSubtitle: { color: '#FFFFFF', fontFamily: fonts.regular, fontSize: fontSizes.sm ?? 12, marginTop: 3 },
  scroll: { flex: 1, backgroundColor: '#FFFFFF', borderTopLeftRadius: 22, borderTopRightRadius: 22 },
  content: { paddingHorizontal: 18, paddingTop: 22, paddingBottom: 42 },
  sectionTitle: { color: colors.text, fontFamily: fonts.semibold, fontSize: fontSizes.lg ?? 17, marginBottom: 5 },
  helper: { color: '#888888', fontFamily: fonts.regular, fontSize: fontSizes.sm ?? 11, lineHeight: 17, marginBottom: 14 },
  weekDayOptions: { flexDirection: 'row', gap: 5, marginBottom: 16 },
  weekDayButton: { flex: 1, minHeight: 52, borderWidth: 1, borderColor: '#E0E0E0', borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF' },
  weekDayButtonActive: { borderColor: orange, backgroundColor: '#FFF0EA' },
  weekDayButtonShort: { color: colors.text, fontFamily: fonts.semibold, fontSize: 12 },
  weekDayButtonLabel: { color: '#999999', fontFamily: fonts.regular, fontSize: 8, marginTop: 2 },
  weekDayButtonTextActive: { color: '#E55318' },
  calendarCard: { borderWidth: 1, borderColor: '#FFD2BF', borderRadius: 16, backgroundColor: '#FFF9F6', padding: 12, marginBottom: 28 },
  calendarHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 },
  calendarArrow: { width: 34, height: 34, alignItems: 'center', justifyContent: 'center', borderRadius: 17, backgroundColor: '#FFFFFF' },
  arrowDisabled: { opacity: 0.3 },
  month: { color: colors.text, fontFamily: fonts.semibold, fontSize: fontSizes.sm ?? 13 },
  calendarWeekDays: { flexDirection: 'row', marginBottom: 6 },
  calendarWeekDayText: { width: '14.28%', color: '#999999', fontFamily: fonts.medium, fontSize: 10, textAlign: 'center' },
  daysGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayButton: { width: '14.28%', height: 39, alignItems: 'center', justifyContent: 'center' },
  dayCircle: { width: 31, height: 31, borderRadius: 16, alignItems: 'center', justifyContent: 'center' },
  dayCircleSelected: { backgroundColor: orange },
  dayCircleSaved: { borderWidth: 2, borderColor: '#16803C' },
  dayText: { color: colors.text, fontFamily: fonts.medium, fontSize: 11 },
  dayTextDisabled: { color: '#D0D0D0' },
  dayTextSelected: { color: '#FFFFFF' },
  savedBadge: { position: 'absolute', right: -3, top: -3, width: 13, height: 13, borderRadius: 7, backgroundColor: '#16803C', alignItems: 'center', justifyContent: 'center' },
  legend: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, marginTop: 10 },
  legendDot: { width: 12, height: 12, borderRadius: 6, backgroundColor: orange },
  legendEmpty: { width: 12, height: 12, borderRadius: 6, borderWidth: 1, borderColor: '#D0D0D0', marginLeft: 10 },
  legendText: { color: '#888888', fontFamily: fonts.regular, fontSize: 9 },
  timeInputRow: { flexDirection: 'row', gap: 9 },
  timeInput: { flex: 1, height: 47, borderWidth: 1, borderColor: '#D5D5D5', borderRadius: 10, paddingHorizontal: 13, color: colors.text, fontFamily: fonts.medium, backgroundColor: '#FFFFFF' },
  addTimeButton: { minWidth: 118, height: 47, borderRadius: 10, backgroundColor: orange, flexDirection: 'row', gap: 5, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  addTimeText: { color: '#FFFFFF', fontFamily: fonts.semibold, fontSize: fontSizes.sm ?? 12 },
  timeChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, minHeight: 48, marginTop: 12, marginBottom: 22 },
  timeChip: { height: 38, borderRadius: 19, borderWidth: 1, borderColor: '#FFB394', backgroundColor: '#FFF6F2', flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: 11 },
  timeChipText: { color: '#E55318', fontFamily: fonts.semibold, fontSize: 12 },
  emptyText: { color: '#999999', fontFamily: fonts.regular, fontSize: fontSizes.sm ?? 11, paddingVertical: 10 },
  summaryCard: { minHeight: 68, borderRadius: 14, backgroundColor: '#FFF0EA', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, marginTop: 4 },
  summaryCardSaved: { backgroundColor: '#ECFDF3', borderWidth: 1, borderColor: '#ABEFC6' },
  summaryText: { flex: 1, marginLeft: 11 },
  summaryTitle: { color: colors.text, fontFamily: fonts.semibold, fontSize: fontSizes.sm ?? 13 },
  summarySubtitle: { color: '#777777', fontFamily: fonts.regular, fontSize: 10, marginTop: 3 },
  savedText: { color: '#16803C', fontFamily: fonts.semibold, fontSize: 10, marginTop: 4 },
  successBanner: { minHeight: 46, borderRadius: 11, borderWidth: 1, borderColor: '#ABEFC6', backgroundColor: '#ECFDF3', flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, marginTop: 12 },
  successText: { flex: 1, color: '#16803C', fontFamily: fonts.medium, fontSize: fontSizes.sm ?? 11 },
  applyButton: { height: 54, borderRadius: 12, backgroundColor: orange, alignItems: 'center', justifyContent: 'center', marginTop: 14 },
  applyButtonText: { color: '#FFFFFF', fontFamily: fonts.semibold, fontSize: fontSizes.md ?? 15 },
  disabled: { opacity: 0.55 },
  loader: { marginTop: 18 },
});
