import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from '../../global';

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: '#FF6B2C' },
  header: { minHeight: 132, backgroundColor: '#FF6B2C', paddingHorizontal: 20, paddingTop: 10 },
  headerText: { marginTop: 16 },
  title: { color: '#FFFFFF', fontFamily: fonts.semibold, fontSize: fontSizes['2xl'] ?? 22 },
  subtitle: { color: '#FFFFFF', fontFamily: fonts.regular, fontSize: fontSizes.sm ?? 12, marginTop: 3 },
  scroll: { flex: 1, backgroundColor: '#FFFFFF', borderTopLeftRadius: 22, borderTopRightRadius: 22 },
  content: { paddingHorizontal: 18, paddingTop: 22, paddingBottom: 36 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  sectionTitle: { color: colors.text, fontFamily: fonts.semibold, fontSize: fontSizes.lg ?? 17 },
  actions: { flexDirection: 'row', gap: 8 },
  editButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#EEEEEE', alignItems: 'center', justifyContent: 'center' },
  addButton: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#FF6B2C', alignItems: 'center', justifyContent: 'center' },
  disabled: { opacity: 0.4 },
  warning: { color: '#B54708', backgroundColor: '#FFFAEB', borderColor: '#FEDF89', borderWidth: 1, borderRadius: 10, padding: 11, fontFamily: fonts.medium, fontSize: fontSizes.sm ?? 11, marginBottom: 14 },
  loader: { marginTop: 30 },
  error: { color: '#B42318', fontFamily: fonts.medium, textAlign: 'center', marginVertical: 18 },
  emptyCard: { minHeight: 80, borderRadius: 14, backgroundColor: '#FFFFFF', justifyContent: 'center', padding: 18, elevation: 3, shadowColor: '#000', shadowOpacity: 0.1, shadowRadius: 5, shadowOffset: { width: 0, height: 2 } },
  emptyText: { color: '#999999', fontFamily: fonts.regular, fontSize: fontSizes.sm ?? 12 },
  card: { borderRadius: 16, borderWidth: 1, borderColor: '#FFD2BF', backgroundColor: '#FFF9F6', padding: 16, marginBottom: 14 },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  cardHeading: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 10 },
  cardTitle: { flex: 1, minWidth: 130, color: colors.text, fontFamily: fonts.semibold, fontSize: fontSizes.lg ?? 16 },
  priceBadge: { minHeight: 30, borderRadius: 15, backgroundColor: '#FFE8DE', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  price: { color: '#E55318', fontFamily: fonts.semibold, fontSize: fontSizes.sm ?? 12 },
  cardEditButton: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#EEEEEE', alignItems: 'center', justifyContent: 'center' },
  description: { color: '#555555', fontFamily: fonts.regular, fontSize: fontSizes.sm ?? 12, lineHeight: 19, marginTop: 13 },
  divider: { height: 1, backgroundColor: '#F1D9CF', marginVertical: 14 },
  detailsRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  detailBadge: { minHeight: 34, flexDirection: 'row', alignItems: 'center', gap: 6, borderRadius: 17, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#F2D2C4', paddingHorizontal: 11 },
  detailText: { color: '#666666', fontFamily: fonts.medium, fontSize: 10 },
  servicesLabel: { color: colors.text, fontFamily: fonts.semibold, fontSize: fontSizes.sm ?? 12, marginTop: 15, marginBottom: 8 },
  serviceChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7 },
  serviceChip: { minHeight: 30, flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: 15, backgroundColor: '#FFECE4', paddingHorizontal: 10 },
  serviceChipText: { color: '#8E3B18', fontFamily: fonts.medium, fontSize: 10 },
  emptyServices: { color: '#999999', fontFamily: fonts.regular, fontSize: 10 },
});
