import { StyleSheet } from 'react-native';
import { colors, fonts, fontSizes } from '../../global';

export const styles = StyleSheet.create({
  trigger: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  overlay: {
    flex: 1,
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
  },
  dismissArea: {
    ...StyleSheet.absoluteFillObject,
  },
  drawerWrapper: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: '84%',
    maxWidth: 350,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000000',
    shadowOffset: { width: 5, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 12,
    elevation: 12,
  },
  drawer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 20,
  },
  userHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    minHeight: 104,
    borderBottomWidth: 1,
    borderBottomColor: '#EEEEEE',
  },
  avatar: {
    width: 58,
    height: 58,
    borderRadius: 29,
    borderWidth: 2,
    backgroundColor: '#D5D5D5',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
  },
  userInfo: {
    flex: 1,
    marginLeft: 12,
  },
  userName: {
    color: colors.text,
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md ?? 15,
  },
  userEmail: {
    color: '#888888',
    fontFamily: fonts.regular,
    fontSize: fontSizes.sm ?? 11,
    marginTop: 3,
  },
  menuTitle: {
    color: '#888888',
    fontFamily: fonts.semibold,
    fontSize: fontSizes.sm ?? 12,
    textTransform: 'uppercase',
    marginTop: 22,
    marginBottom: 8,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F1F1F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  item: {
    width: '100%',
    minHeight: 52,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    borderRadius: 12,
    paddingHorizontal: 8,
    marginBottom: 4,
  },
  itemIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itemText: {
    flex: 1,
    color: colors.text,
    fontFamily: fonts.medium,
    fontSize: fontSizes.sm ?? 13,
  },
  items: {
    width: '100%',
  },
  footer: {
    marginTop: 'auto',
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE',
  },
  logoutButton: {
    width: '100%',
    height: 50,
    marginTop: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: '#D92D20',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 9,
  },
  logoutText: {
    color: '#D92D20',
    fontFamily: fonts.semibold,
    fontSize: fontSizes.md ?? 14,
  },
});
